<?php

namespace App\Http\Controllers\Api\Install;

use App\Http\Controllers\Controller;
use App\Models\ImageServer;
use App\Models\Node;
use App\Services\DeployTokenService;
use App\Services\EncryptionService;
use App\Services\NodeAuthService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

class DeployController extends Controller
{
    public function __construct(
        private readonly DeployTokenService $deployTokens,
        private readonly NodeAuthService $nodeAuth,
        private readonly EncryptionService $encryption,
    ) {}

    public function nodeScript(string $token): Response
    {
        $deploy = $this->requireToken($token, DeployTokenService::PURPOSE_NODE);
        $panelUrl = $this->deployTokens->panelUrl();
        $plain = $token;

        $exports = '';
        if ($deploy->resource instanceof Node) {
            $node = $deploy->resource;
            $pmaDomain = '';
            if (filled($node->phpmyadmin_url)) {
                $pmaHost = parse_url((string) $node->phpmyadmin_url, PHP_URL_HOST);
                if (is_string($pmaHost) && $pmaHost !== '' && filter_var($pmaHost, FILTER_VALIDATE_IP) === false) {
                    $pmaDomain = $pmaHost;
                }
            }
            if ($pmaDomain === '') {
                $host = trim((string) $node->hostname);
                if ($host !== '' && str_contains($host, '.') && filter_var($host, FILTER_VALIDATE_IP) === false) {
                    $pmaDomain = $host;
                }
            }
            if ($pmaDomain !== '') {
                $safe = str_replace(['"', "'", "\n", "\r", '\\'], '', $pmaDomain);
                $exports .= "export GAMEPANEL_PHPMYADMIN_DOMAIN=\"{$safe}\"\n";
                $exports .= "export GAMEPANEL_NODE_FQDN=\"{$safe}\"\n";
            }
        }

        $script = <<<BASH
#!/usr/bin/env bash
# GamePanel Node Auto-Deploy (generated by panel)
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
PANEL_URL="{$panelUrl}"
DEPLOY_TOKEN="{$plain}"
REPO_URL="\${GAMEPANEL_REPO_URL:-https://github.com/nycon/gameinterface.git}"
SRC_DIR="\${GAMEPANEL_SOURCE_DIR:-/opt/gamepanel-src}"
{$exports}
if [[ "\${EUID:-0}" -ne 0 ]]; then
  echo "Bitte als root ausführen (sudo)." >&2
  exit 1
fi

apt-get update -qq
apt-get install -y -qq git curl ca-certificates >/dev/null

if [[ -d "\${SRC_DIR}/.git" ]]; then
  git -C "\$SRC_DIR" fetch --depth 1 origin main 2>/dev/null || true
  git -C "\$SRC_DIR" reset --hard origin/main 2>/dev/null || true
elif [[ -x "\${SRC_DIR}/install.sh" ]]; then
  true
else
  rm -rf "\$SRC_DIR"
  git clone --depth 1 "\$REPO_URL" "\$SRC_DIR"
fi

cd "\$SRC_DIR"
exec ./install.sh --role node --non-interactive \\
  --panel-url "\$PANEL_URL" \\
  --deploy-token "\$DEPLOY_TOKEN" \\
  --tls-insecure
BASH;

        return response($script, 200, [
            'Content-Type' => 'text/x-shellscript; charset=UTF-8',
            'Cache-Control' => 'no-store',
        ]);
    }

    public function imageServerScript(string $token): Response
    {
        $deploy = $this->requireToken($token, DeployTokenService::PURPOSE_IMAGE_SERVER);
        $panelUrl = $this->deployTokens->panelUrl();
        $plain = $token;

        $script = <<<BASH
#!/usr/bin/env bash
# GamePanel Image-Server Auto-Deploy (generated by panel)
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
PANEL_URL="{$panelUrl}"
DEPLOY_TOKEN="{$plain}"
REPO_URL="\${GAMEPANEL_REPO_URL:-https://github.com/nycon/gameinterface.git}"
SRC_DIR="\${GAMEPANEL_SOURCE_DIR:-/opt/gamepanel-src}"

if [[ "\${EUID:-0}" -ne 0 ]]; then
  echo "Bitte als root ausführen (sudo)." >&2
  exit 1
fi

apt-get update -qq
apt-get install -y -qq git curl ca-certificates >/dev/null

if [[ -d "\${SRC_DIR}/.git" ]]; then
  git -C "\$SRC_DIR" fetch --depth 1 origin main 2>/dev/null || true
  git -C "\$SRC_DIR" reset --hard origin/main 2>/dev/null || true
elif [[ -x "\${SRC_DIR}/install.sh" ]]; then
  true
else
  rm -rf "\$SRC_DIR"
  git clone --depth 1 "\$REPO_URL" "\$SRC_DIR"
fi

cd "\$SRC_DIR"
exec ./install.sh --role image-server --non-interactive \\
  --panel-url "\$PANEL_URL" \\
  --deploy-token "\$DEPLOY_TOKEN"
BASH;

        return response($script, 200, [
            'Content-Type' => 'text/x-shellscript; charset=UTF-8',
            'Cache-Control' => 'no-store',
        ]);
    }

    public function claimNode(Request $request): JsonResponse
    {
        $data = $request->validate([
            'deploy_token' => ['required', 'string'],
            'hostname' => ['nullable', 'string', 'max:255'],
            'ip_address' => ['nullable', 'ip'],
            'agent_version' => ['nullable', 'string', 'max:64'],
            'fqdn' => ['nullable', 'string', 'max:255'],
            'tls_insecure' => ['nullable', 'boolean'],
            'phpmyadmin_url' => ['nullable', 'string', 'max:255'],
            'mysql_username' => ['nullable', 'string', 'max:64'],
            'mysql_password' => ['nullable', 'string', 'max:255'],
        ]);

        $deploy = $this->requireToken($data['deploy_token'], DeployTokenService::PURPOSE_NODE);
        /** @var Node $node */
        $node = $deploy->resource;
        if (! $node instanceof Node) {
            throw new HttpException(404, 'Node not found for deploy token');
        }

        $updates = array_filter([
            'hostname' => $data['hostname'] ?? null,
            'ip_address' => $data['ip_address'] ?? null,
            'agent_version' => $data['agent_version'] ?? null,
            'phpmyadmin_url' => $data['phpmyadmin_url'] ?? null,
            'mysql_admin_user' => $data['mysql_username'] ?? null,
            'status' => 'offline',
        ], fn ($v) => $v !== null && $v !== '');

        if (! empty($data['mysql_password'])) {
            $updates['mysql_admin_password_encrypted'] = $this->encryption->encrypt($data['mysql_password']);
        }

        if ($updates !== []) {
            $node->update($updates);
        }

        $agent = $this->nodeAuth->createToken($node, 'agent');
        $this->deployTokens->consume($deploy);

        $panelUrl = $this->deployTokens->panelUrl();
        $image = ImageServer::query()->where('is_active', true)->where('status', 'ready')->latest()->first();

        $tlsInsecure = $request->boolean('tls_insecure')
            || str_contains($panelUrl, '127.0.0.1')
            || preg_match('/^https?:\/\/\d+\.\d+\.\d+\.\d+/', $panelUrl) === 1;

        $config = $this->buildAgentConfigYaml(
            panelUrl: $panelUrl,
            node: $node,
            agentToken: $agent['token'],
            imageServer: $image,
            tlsInsecure: $tlsInsecure,
        );

        return response()->json([
            'node' => $node->fresh(),
            'token' => $agent['token'],
            'panel_url' => $panelUrl,
            'config_yaml' => $config,
            'image_server' => $image ? [
                'host' => $image->hostname,
                'port' => $image->port,
                'username' => $image->username,
                'base_path' => $image->base_path,
                'protocol' => $image->protocol,
                'private_key' => $this->encryption->decrypt($image->ssh_key_encrypted),
                'password' => $this->encryption->decrypt($image->password_encrypted),
            ] : null,
        ]);
    }

    public function claimImageServer(Request $request): JsonResponse
    {
        $data = $request->validate([
            'deploy_token' => ['required', 'string'],
        ]);

        $deploy = $this->requireToken($data['deploy_token'], DeployTokenService::PURPOSE_IMAGE_SERVER);
        /** @var ImageServer $server */
        $server = $deploy->resource;
        if (! $server instanceof ImageServer) {
            throw new HttpException(404, 'Image server not found for deploy token');
        }

        return response()->json([
            'image_server' => $server,
            'panel_url' => $this->deployTokens->panelUrl(),
            'suggested' => [
                'username' => $server->username ?: 'gamepanel-images',
                'base_path' => $server->base_path ?: '/images',
                'port' => $server->port ?: 22,
                'protocol' => $server->protocol ?: 'sftp',
                'root' => '/srv/gamepanel-images',
            ],
        ]);
    }

    public function completeImageServer(Request $request): JsonResponse
    {
        $data = $request->validate([
            'deploy_token' => ['required', 'string'],
            'hostname' => ['required', 'string', 'max:255'],
            'port' => ['nullable', 'integer', 'min:1', 'max:65535'],
            'username' => ['required', 'string', 'max:255'],
            'base_path' => ['nullable', 'string', 'max:255'],
            'protocol' => ['nullable', 'in:sftp,ftps,ftp'],
            'ssh_private_key' => ['nullable', 'string'],
            'password' => ['nullable', 'string'],
            'public_url' => ['nullable', 'string', 'max:255'],
        ]);

        if (empty($data['ssh_private_key']) && empty($data['password'])) {
            return response()->json(['message' => 'ssh_private_key or password required'], 422);
        }

        $deploy = $this->requireToken($data['deploy_token'], DeployTokenService::PURPOSE_IMAGE_SERVER);
        /** @var ImageServer $server */
        $server = $deploy->resource;
        if (! $server instanceof ImageServer) {
            throw new HttpException(404, 'Image server not found for deploy token');
        }

        $server->update([
            'hostname' => $data['hostname'],
            'port' => $data['port'] ?? 22,
            'username' => $data['username'],
            'base_path' => $data['base_path'] ?? '/images',
            'protocol' => $data['protocol'] ?? 'sftp',
            'public_url' => $data['public_url'] ?? null,
            'password_encrypted' => $this->encryption->encrypt($data['password'] ?? null),
            'ssh_key_encrypted' => $this->encryption->encrypt($data['ssh_private_key'] ?? null),
            'is_active' => true,
            'status' => 'ready',
        ]);

        $this->deployTokens->consume($deploy);

        return response()->json([
            'image_server' => $server->fresh(),
            'ok' => true,
        ]);
    }

    private function requireToken(string $plain, string $purpose): \App\Models\DeployToken
    {
        $deploy = $this->deployTokens->findValid($plain, $purpose);
        if (! $deploy) {
            throw new HttpException(403, 'Invalid or expired deploy token');
        }

        $deploy->load('resource');

        return $deploy;
    }

    private function buildAgentConfigYaml(
        string $panelUrl,
        Node $node,
        string $agentToken,
        ?ImageServer $imageServer,
        bool $tlsInsecure = false,
    ): string {
        $tls = $tlsInsecure ? 'true' : 'false';

        $imgHost = $imageServer?->hostname ?? '';
        $imgPort = $imageServer?->port ?? 22;
        $imgUser = $imageServer?->username ?? 'gamepanel-images';

        return <<<YAML
panel:
  url: "{$panelUrl}"
  timeout: 30s
  tls_insecure: {$tls}

node:
  id: "{$node->uuid}"
  token: "{$agentToken}"
  name: "{$node->name}"
  fqdn: "{$node->hostname}"

paths:
  agent_dir: "/opt/gamepanel/agent"
  servers_dir: "/srv/gamepanel/servers"
  images_dir: "/srv/gamepanel/images"
  backups_dir: "/srv/gamepanel/backups"
  steamcmd_dir: "/opt/gamepanel/steamcmd"
  logs_dir: "/var/log/gamepanel"

agent:
  heartbeat_interval: 30s
  job_poll_interval: 5s
  data_dir: "/opt/gamepanel/agent/data"

systemd:
  unit_prefix: "gamepanel-server"
  slice: "gamepanel.slice"

firewall:
  backend: "nftables"
  table: "gamepanel"
  chain: "allocations"

database:
  engine: "mariadb"
  host: "127.0.0.1"
  port: 3306
  username: "gamepanel-agent"
  password: "__MYSQL_PASSWORD__"

sftp:
  enabled: true
  host: "{$imgHost}"
  port: {$imgPort}
  username: "{$imgUser}"
  password: ""
  private_key_path: "/etc/gamepanel/keys/image-server"
  known_hosts_path: ""
  remote_base: "/images"

ftp:
  enabled: false

logging:
  level: "info"
  format: "json"
  file: "/var/log/gamepanel/agent.log"

scripts:
  timeout: 5m
  allowed_interpreters:
    - "/bin/bash"
    - "/bin/sh"
  sandbox:
    drop_capabilities: true
    no_new_privileges: true
    read_only_paths:
      - "/usr"
      - "/lib"
      - "/lib64"
YAML;
    }
}
